### PR TITLE
Fixing images by removing protocol.

### LINKED ISSUE #5: Chrome Extension Broken
In the newer browser versions, since this awesome extension and bookmarklet was released, http requests on https sites are not allowed.  All the image replacements turn into broken images.  The fix would be to change all the urls from `http://heygirl.io/...` to `//heygirl.io/...`

The `//` at the beginning without the protocol lets the browser use protocol inference (whatever the existing page's protocol is).  I will be able to open a PR after work in a few hours if nobody gets to this before me.

Thanks,
Nick Stewart

### PR DESCRIPTION
**Pull request by nickstew**
Changed all images to use protocol inference.  
Source server for images [heygirl.io](http://heygirl.io) needs a HTTPS cert before anything will be fixed.

Fixes #5

### CODE REVIEW

**Comment by jenkoian** [comment]
This is the greatest project I've ever come across, please consider merging this 🤞

**Comment by jenkoian** [comment]
Had some time so tried this out but it won't work because the images aren't available over https.

**Comment by jenkoian** [comment]
@nickstew would be up for supporting a fork if @keccers has abandoned.

**Comment by nickstew** [comment]
Actually if we base64 encode all the images instead of relying on the server to send them to the client, we could avoid this mess and images would load much faster.  Feel free to submit a PR to my repo if I don't get around to working on this.  A simple script that goes thru the array of images and converts them would take a few minutes to write and copy the output.  I've got a few different projects I'm juggling at the moment, but it would be nice to wrap up some of these loose ends.  I would appreciate any assistance.  ❤️ 

```javascript
const base64Images = {};
const images = ['http://example.com/image.jpg'];
Promise.all(images.map(image => 
fetch(image)
  .then(response => response.blob())
  .then(myBlob =>
    base64Images[image] = URL.createObjectURL(myBlob)
  )
).then(() => 
  console.log(base64Images)
);
```

**Comment by keccers** [comment]
I abandoned my entire Github account for awhile and am finally getting around to cleaning some of this up — I sincerely apologize, @nickstew, @jenkoian, for my many-years delay. 

I merged this PR and also will double back on what's actually in the Chrome Store after taking a look at implementing Base64 encoding. That's a great idea.

**Comment by nickstew** [comment]
OMG!  Welcome back!  Glad I could help!

**Pull request merged**
